### ISSUE TITLE
Update officers

### ISSUE THREAD

**Issue by magical** [OSULUG/OSULUG-Website#136]
Need to update the contact page to list the new officers.  http://lug.oregonstate.edu/contact/

AFAIK, the results of the election last week were as follows:

- President: Drew Ortega
- Vice President: Lindsey Kvarfordt
- Secretary: Jaelyn Litzinger
- Public Relations: Arthur York
- Treasurer: Vance

**Comment by drewsortega** [comment]
PR #137
