### ISSUE TITLE
form letters should explain why to join

### ISSUE THREAD

**Issue by edunham** [OSULUG/OSULUG-Website#44]
talked to Bear about why he didn't join LUG earlier even though he got the emails, and he says a link from the form letters to classes explaining more about what LUG does would have helped. We should write that explanation and then link it from the letter.

**Comment by lucywyman** [comment]
Do you think editing the blurb above the fold of http://lug.oregonstate.edu is the best way to do that? Or have a separate blog post? I'm reasonably certain that we link to lug.o.e from our fliers, if not we *really* should.  The biggest problem is that lug is different things to different people and changes with time, so ymmv and anything we write now might not be true next fall, beyond what's already on the LUG site :/  Is there anything we're missing/that's hard to find?

**Comment by ElijahCaine** [comment]
@edunham Can you specify where exactly Bear looked for information so we can be sure to plaster info on that part of the website/emails/meatspace?

**Comment by edunham** [comment]
@ElijahCaine Sorry, after 2 years I do not recall the exact details of our conversation. I believe the extent of his involvement was reading the email that we sent to the class list. The emails which were sent to the list at that time are documented in https://github.com/OSULUG/OSULUG-Website/blob/master/content/guides/installfest.mkd , so that would be the file to improve unless you've fixed the workflow around form letters since I left.

**Comment by lucywyman** [comment]
Question: What is a form letter?

Other question: Since it sounds like this hasn't been a recurring issue in 2 years, can we close this issue?

**Comment by edunham** [comment]
form letter, noun.     a standardized letter to deal with frequently occurring matters.

They are the templates for how to do publicity which I created years ago in the hopes of making publicity easier for future lug admins. If they are no longer in use, this issue should be closed.
