### ISSUE TITLE
Group ``/events/`` contents from each term into own directory

### ISSUE THREAD

**Issue by lucywyman** [OSULUG/OSULUG-Website#79]
So directory structure would be:

├── events
│   ├── fall-2011
│       ├── 20160329_wk1.mkd
│       ├── 20160405_wk2.mkd
│       ├── 20160412_wk3.mkd
│   ├── winter-2011
│   ├── spring-2011

This may be more complicated than expected.  We could alternatively convert the site to Pelican/other SSG.

**Comment by ElijahCaine** [comment]
This issue was resolved with commit 1bfc15c7a3d700e95759945fae8d739c77693500 to master. I didn't organize every event by season, just the events for 2016. Every other year has been organized by year.
